### ISSUE TITLE
Minor typo in the docstring for dumpFile

### ISSUE THREAD

**Issue by billtubbs** [MartinKoch123/yaml#13]
I think there is a typo in the help text of [yaml.dumpFile](https://github.com/MartinKoch123/yaml/blob/bf2c95422da6395aa52c6d8c3eaf8d02a53c7fa4/%2Byaml/dumpFile.m#L6):

```lang-none
>> help yaml.dumpFile
  dumpFile Write data to YAML file.
    yaml.dumpFile(FILE, DATA) converts DATA to YAML and saves it in a new
    file FILE.
 
    yaml.dumpFile(DATA, STYLE) uses a specific output style.
    STYLE can be "auto" (default), "block" or "flow".
```

I think the second case should be `yaml.dumpFile(FILE, DATA, STYLE)`

**Comment by MartinKoch123** [comment]
Fixed it, thanks for the hint!
