### ISSUE TITLE
Unusual line continuation behaviour with yaml.Null

### ISSUE THREAD

**Issue by billtubbs** [MartinKoch123/yaml#3]
This is fairly minor, but the line break and continuation seems a little premature for an array of Nulls:

```matlab
>> yaml.dump({yaml.Null, yaml.Null, yaml.Null, yaml.Null, yaml.Null})

ans = 

    "[null, null, null, null,
       null]
     "

```

**Comment by MartinKoch123** [comment]
I fixed that and made a new release. It was related to the work around I had to use to dump nulls. Thanks for pointing it out.
