### ISSUE TITLE
How do I parse this .yml format file?

### ISSUE THREAD

**Issue by cuixing158** [MartinKoch123/yaml#4]
hi, I need to parse such a .yml file into matlab, or later I need to save the variables in matlab in similar .yml format, but I can't import and export successfully, I expect the author to enhance this function!
```matlab
s = yaml.loadFile("cam_proj_CAM_FRONT.yml");
```
The output error message is as follows:
```text
Error using yaml.load
Failed to load YAML string.
Error in yaml.loadFile (line 44)
result = yaml.load(content, "ConvertToArray", options.ConvertToArray);
Caused by:
    Error using yaml.load
...
```
[cam_proj_CAM_FRONT.zip](https://github.com/MartinKoch123/yaml/files/8888569/cam_proj_CAM_FRONT.zip)

  
[Link to question information](https://ww2.mathworks.cn/matlabcentral/answers/686498-how-to-effectively-read-yml-files-as-structures#comment_2211735)

**Comment by MartinKoch123** [comment]
Hey, Im sorry you are having trouble with the tool. I wont be able to investige the issue until next week. Maybe you can try and see if you can read subparts of the file until I can fix it.

**Comment by MartinKoch123** [comment]
Hi @cuixing158 ,
there are two problems:
 - The underlying SnakeYAML is written for YAML 1.1 for which the first line `%YAML:1.0` is not valid (`%YAML 1.0` without `:` would be acceptable). I will update the documentation to mention YAML 1.1.
 - The custom opencv types are not supported.

You can build a workaround like this:
 - Read file into string with `fileread`
 - Delete all text occurrences of `%YAML:1.0` and `!!opencv-matrix` (e.g. with `strrep`)
 - Parse modified string with `yaml.load`
 - Manually convert the content of the `data` field to a 2D array (e.g. with `reshape`)

To write YAML files in the same format you have to reverse the above process. However, it will not be formatted such that every row is in a new line.
