### ISSUE TITLE
Cannot find 'Yaml' function

### ISSUE THREAD

**Issue by jambo6** [MartinKoch123/yaml#6]
I'm getting this error
```
Unrecognized function or variable 'Yaml'.
 
44      MException("yaml:load:Failed", "Failed to load YAML string.").addCause(cause).throw
```
any ideas where this function is supposed to be located?

**Comment by jambo6** [comment]
Sorry, not an issue with this, following here helped
https://uk.mathworks.com/matlabcentral/answers/96005-why-do-i-get-the-error-undefined-function-or-variable

**Comment by MartinKoch123** [comment]
Hi @jambo6, 
I only found the time to answer today but I'm glad it works now for you. Would you mind giving a bit more details about the solution? I was trying to reproduce your error, but didn't know how. Maybe I could add something to the documentation the prevent others from having the same trouble.
