### ISSUE TITLE
YAML 1.2 

### ISSUE THREAD

**Issue by qlahcim** [MartinKoch123/yaml#8]
Do you plan to upgrade your yaml parser for MATLAB to be compatible with YAML 1.2 specs via latest snakeyaml-engine?

**Comment by MartinKoch123** [comment]
Good idea, I'll look into it.

**Comment by qlahcim** [comment]
Thanks in advance ... :)

**Comment by MartinKoch123** [comment]
@michalkvasnicka: If you like you can use [this branch](/MartinKoch123/yaml/tree/yaml-1.2) where updated to snakeyaml engine 2.3 which supports YAML 1.2. However, I noticed some odd behaviour, e.g., `~` or `True` is not recognized as `null` and boolean `true` which is why I did not merge it yet.
